## Import packages

In [1]:
import os
import numpy as np
import rasterio
import pandas as pd

In [3]:
def convert_tif_to_npy(tif_path):
    # Generate the .npy filename
    npy_path = os.path.splitext(tif_path)[0] + '.npy'

    # Check if the .npy file already exists
    if os.path.exists(npy_path):
        print(f"Skipping {tif_path} as {npy_path} already exists")
        return
    
    with rasterio.open(tif_path) as src:
        img = src.read()
        np.save(npy_path, img)
    
    print(f"Converted {tif_path} to {npy_path}")


In [4]:
# Example usage
convert_tif_to_npy('../data_layers_single/ndvi/ndvi_id2005_index_1_t2_2018-07-25_hr_11.tif')

Skipping ../data_layers_single/ndvi/ndvi_id2005_index_1_t2_2018-07-25_hr_11.tif as ../data_layers_single/ndvi/ndvi_id2005_index_1_t2_2018-07-25_hr_11.npy already exists


In [4]:
# read in the .npy file
img = np.load('../data_layers_single/ndvi/ndvi_id2005_index_1_t2_2018-07-25_hr_11.npy')
print(img.shape)
print(img)

(1, 101, 101)
[[[0.62448275 0.6218304  0.6090012  ... 0.6281635  0.6364854  0.63820636]
  [0.61254686 0.6158266  0.60383445 ... 0.63529193 0.6367698  0.63712084]
  [0.60717446 0.60216236 0.5877266  ... 0.62671566 0.6257723  0.6246104 ]
  ...
  [0.5954609  0.58423525 0.5718299  ... 0.6301174  0.62513494 0.60891765]
  [0.5999506  0.5778378  0.57568336 ... 0.63124436 0.63029844 0.61173224]
  [0.6151915  0.597685   0.5949887  ... 0.6371749  0.6414175  0.6429343 ]]]


In [5]:
def convert_all_tifs_in_directory(directory):
    for filename in os.listdir(directory):
        if filename.endswith('.tif'):
            tif_path = os.path.join(directory, filename)
            convert_tif_to_npy(tif_path)


In [ ]:
# Example usage
convert_all_tifs_in_directory('../data_layers_single/ndvi/')

In [ ]:
# Example usage
convert_all_tifs_in_directory('../data_layers_single/canopy/')

In [ ]:
# Example usage
convert_all_tifs_in_directory('../data_layers_single/herby/')

In [ ]:
# Example usage
convert_all_tifs_in_directory('../data_layers_single/slope/')

In [ ]:
# Example usage
convert_all_tifs_in_directory('../data_layers_single/pres/')

# Update the filenames in the csv

In [9]:
def update_filenames_in_csv(input_csv_path, output_csv_suffix='_npy'):
    # Read the original CSV file
    df = pd.read_csv(input_csv_path)
    
    # Function to replace .tif extension with .npy
    def replace_extension(filename):
        return os.path.splitext(filename)[0] + '.npy'
    
    # Assuming that the filenames are in specific columns, update those columns
    for column in df.columns:
        if df[column].dtype == object:  # Check if the column contains string data
            df[column] = df[column].apply(lambda x: replace_extension(x) if x.endswith('.tif') else x)
    
    # Generate the output CSV filename
    output_csv_path = os.path.splitext(input_csv_path)[0] + output_csv_suffix + '.csv'
    
    # Save the updated DataFrame to the new CSV file
    df.to_csv(output_csv_path, index=False)
    print(f"Updated CSV saved as: {output_csv_path}")


In [10]:
# Example usage
update_filenames_in_csv('../data_layers_single/buffalo_all_101x101_data_df_lag_1hr_n103630.csv')

Updated CSV saved as: ../data_layers_single/buffalo_all_101x101_data_df_lag_1hr_n103630_npy.csv
