## Import packages

In [1]:
import os
import numpy as np
import rasterio

In [3]:
def convert_tif_to_npy(tif_path):
    # Generate the .npy filename
    npy_path = os.path.splitext(tif_path)[0] + '.npy'
    
    with rasterio.open(tif_path) as src:
        img = src.read()
        np.save(npy_path, img)
    
    print(f"Converted {tif_path} to {npy_path}")


In [5]:
# Example usage
convert_tif_to_npy('../data_layers_single/ndvi/ndvi_id2005_index_1_t2_2018-07-25_hr_11.tif')

Converted ../data_layers_single/ndvi/ndvi_id2005_index_1_t2_2018-07-25_hr_11.tif to ../data_layers_single/ndvi/ndvi_id2005_index_1_t2_2018-07-25_hr_11.npy


In [6]:
# read in the .npy file
img = np.load('../data_layers_single/ndvi/ndvi_id2005_index_1_t2_2018-07-25_hr_11.npy')
print(img.shape)
print(img)

(1, 101, 101)
[[[0.62448275 0.6218304  0.6090012  ... 0.6281635  0.6364854  0.63820636]
  [0.61254686 0.6158266  0.60383445 ... 0.63529193 0.6367698  0.63712084]
  [0.60717446 0.60216236 0.5877266  ... 0.62671566 0.6257723  0.6246104 ]
  ...
  [0.5954609  0.58423525 0.5718299  ... 0.6301174  0.62513494 0.60891765]
  [0.5999506  0.5778378  0.57568336 ... 0.63124436 0.63029844 0.61173224]
  [0.6151915  0.597685   0.5949887  ... 0.6371749  0.6414175  0.6429343 ]]]
